// export const words = [
//     [

//         "Dog",
//         "Cat",
//         "House",
//         "Car",
//         "Book",
//         "Table",
//         "Chair",
//         "Tree",
//         "Sun",
//         "Moon",
//         "Ball",
//         "Bird",
//         "Fish",
//         "Computer",
//         "Phone",
//         "Flower",
//         "River",
//         "Mountain",
//         "Ocean",
//         "Beach",
//         "Sky",
//         "Cloud",
//         "Hat",
//         "Shoe",
//         "Sock",
//         "Shirt",
//         "Pants",
//         "Dress",
//         "Jacket",
//         "Backpack",
//         "Wallet",
//         "Key",
//         "Door",
//         "Window",
//         "Bed",
//         "Pillow",
//         "Blanket",
//         "Lamp",
//         "Clock",
//         "Tablecloth",
//         "Plate",
//         "Fork",
//         "Spoon",
//         "Knife",
//         "Cup",
//         "Bowl",
//         "Television",
//         "Radio",
//         "Guitar",
//         "Piano",
//     ],
//     [

//         "Run",
//         "Eat",
//         "Sleep",
//         "Jump",
//         "Talk",
//         "Write",
//         "Read",
//         "Drive",
//         "Swim",
//         "Dance",
//         "Sing",
//         "Cook",
//         "Study",
//         "Work",
//         "Play",
//         "Fly",
//         "Climb",
//         "Laugh",
//         "Cry",
//         "Think",
//         "Listen",
//         "Watch",
//         "Travel",
//         "Hike",
//         "Surf",
//         "Paint",
//         "Draw",
//         "Build",
//         "Create",
//         "Plant",
//         "Grow",
//         "Solve",
//         "Solve",
//         "Ride",
//         "Skate",
//         "Skateboard",
//         "Jump",
//         "Skip",
//         "Skate",
//         "Skip",
//         "Skateboard",
//         "Jump",
//         "Skateboard",
//         "Skip",
//         "Skate",
//         "Skip",
//         "Skateboard",
//         "Jump",
//         "Skip",
//         "Skate",
//     ],
//     [
//         "Big",
//         "Small",
//         "Happy",
//         "Sad",
//         "Fast",
//         "Slow",
//         "Beautiful",
//         "Ugly",
//         "Bright",
//         "Dark",
//         "Hot",
//         "Cold",
//         "Tall",
//         "Short",
//         "Long",
//         "Short",
//         "Heavy",
//         "Light",
//         "Strong",
//         "Weak",
//         "Loud",
//         "Quiet",
//         "Clean",
//         "Dirty",
//         "Hard",
//         "Soft",
//         "Smooth",
//         "Rough",
//         "Sweet",
//         "Sour",
//         "Bitter",
//         "Spicy",
//         "Salty",
//         "Fresh",
//         "Stale",
//         "Sharp",
//         "Dull",
//         "Thin",
//         "Thick",
//         "Narrow",
//         "Wide",
//         "Round",
//         "Square",
//         "Triangle",
//         "Oval",
//         "Straight",
//         "Curved",
//         "Shiny",
//         "Dull",
//         "Glossy ",
//     ],
//     [
//         "Quickly",
//         "Slowly",
//         "Happily",
//         "Sadly",
//         "Quietly",
//         "Loudly",
//         "Carefully",
//         "Carelessly",
//         "Suddenly",
//         "Eventually",
//         "Frequently",
//         "Rarely",
//         "Always",
//         "Never",
//         "Often",
//         "Sometimes",
//         "Seldom",
//         "Immediately",
//         "Shortly",
//         "Longingly",
//         "Briefly",
//         "Angrily",
//         "Calmly",
//         "Nervously",
//         "Excitedly",
//         "Cautiously",
//         "Briskly",
//         "Lazily",
//         "Patiently",
//         "Impatiently",
//         "Quickly",
//         "Slowly",
//         "Happily",
//         "Sadly",
//         "Quietly",
//         "Loudly",
//         "Carefully",
//         "Carelessly",
//         "Suddenly",
//         "Eventually",
//         "Frequently",
//         "Rarely",
//         "Always",
//         "Never",
//         "Often",
//         "Sometimes",
//         "Seldom",
//         "Immediately",
//         "Shortly",
//         "Longingly",
//     ],
//     [
//         "In",
//         "On",
//         "Under",
//         "Over",
//         "Beside",
//         "Behind",
//         "Above",
//         "Below",
//         "Between",
//         "Among",
//         "Before",
//         "After",
//         "Inside",
//         "Outside",
//         "Near",
//         "Far",
//         "Across",
//         "Along",
//         "Through",
//         "Towards",
//         "Away",
//         "Against",
//         "Within",
//         "Without",
//         "Throughout",
//         "Despite",
//         "Except",
//         "During",
//         "Until",
//         "Upon",
//         "Around",
//         "Beneath",
//         "Onto",
//         "Alongside",
//         "Underneath",
//     ]
//     [
//         "And",
//         "But",
//         "Or",
//         "So",
//         "Yet",
//         "However",
//         "Because",
//         "Although",
//         "While",
//         "Since",
//         "Unless",
//         "Whether",
//         "Whereas",
//         "Nevertheless",
//         "Moreover",
//         "Furthermore",
//         "Consequently",
//         "Accordingly",
//         "Therefore",
//         "Hence",
//         "Thus",
//         "Otherwise",
//         "Instead",
//         "Nonetheless",
//         "Notwithstanding",
//         "Though",
//     ]
// ];


export const words = [
    "a",
    "again",
    "all",
    "also",
    "and",
    "another",
    "any",
    "around",
    "as",
    "ask",
    "at",
    "back",
    "because",
    "become",
    "before",
    "begin",
    "both",
    "but",
    "by",
    "call",
    "can",
    "change",
    "child",
    "come",
    "could",
    "course",
    "day",
    "develop",
    "each",
    "early",
    "end",
    "even",
    "eye",
    "face",
    "fact",
    "few",
    "first",
    "follow",
    "from",
    "general",
    "get",
    "give",
    "good",
    "govern",
    "group",
    "hand",
    "have",
    "he",
    "head",
    "help",
    "here",
    "high",
    "hold",
    "home",
    "how",
    "however",
    "if",
    "increase",
    "interest",
    "it",
    "know",
    "large",
    "last",
    "lead",
    "leave",
    "life",
    "like",
    "line",
    "little",
    "look",
    "make",
    "man",
    "may",
    "mean",
    "might",
    "more",
    "must",
    "need",
    "never",
    "new",
    "no",
    "now",
    "number",
    "of",
    "off",
    "old",
    "on",
    "one",
    "open",
    "or",
    "order",
    "out",
    "over",
    "own",
    "part",
    "people",
    "person",
    "place",
    "plan",
    "play",
    "point",
    "possible",
    "present",
    "problem",
    "program",
    "public",
    "real",
    "right",
    "run",
    "say",
    "see",
    "seem",
    "show",
    "small",
    "some",
    "stand",
    "state",
    "still",
    "such",
    "system",
    "take",
    "than",
    "that",
    "the",
    "then",
    "there",
    "these",
    "they",
    "thing",
    "think",
    "this",
    "those",
    "time",
    "to",
    "under",
    "up",
    "use",
    "very",
    "way",
    "what",
    "when",
    "where",
    "while",
    "will",
    "with",
    "without",
    "work",
    "world",
    "would",
    "write",
    "you",
    "she",
    "set",
    "we",
    "long",
    "in",
    "many",
    "do",
    "after",
    "which",
    "so",
    "same",
    "other",
    "house",
    "during",
    "much",
    "just",
    "consider",
    "since",
    "should",
    "only",
    "tell",
    "about"
  ]